Practical 8
Rutvi25/React-Practicals pull request #9
Opened 2022-04-05 09:53 UTC by Rutvi25

![Screenshot from 2022-04-05 15-14-02](https://user-images.githubusercontent.com/97082690/161728304-b95951f2-c2e0-4391-a0f4-fbcb8afb51fa.png)

![Screenshot from 2022-04-05 15-14-35](https://user-images.githubusercontent.com/97082690/161728315-23cb38cb-7448-47a2-a618-62afe4394279.png)

https://user-images.githubusercontent.com/97082690/161728340-2bf0734d-1aee-47be-bfee-cf7693d58e25.mp4

2022-04-06 08:03 UTC, desaianiruddh commented on Practical-8/user-management-react-app/src/App.css
> +  min-height: 100vh;
use px instead of vh if other else places you've used px

2022-04-06 08:30 UTC, desaianiruddh commented on Practical-8/user-management-react-app/src/components/SignUp/SignUp.js
> +    errors.file = 'file size is greater than 2 MB';
error message should be like "File size must lesser than 2 MB"

2022-04-06 08:31 UTC, desaianiruddh commented on Practical-8/user-management-react-app/src/components/SignUp/SignUp.js
> +  } else if (values.file.type !== "image/jpg" && values.file.type !== "image/png") {
add jpeg format

2022-04-06 08:35 UTC, desaianiruddh commented on Practical-8/user-management-react-app/src/index.css
> +  -webkit-font-smoothing: antialiased;
remove css if it's unnecessary

2022-04-06 08:36 UTC, desaianiruddh commented on Practical-8/user-management-react-app/src/reducers/index.js
> +import { combineReducers } from 'redux';
put blank line between internal and external library import call

2022-04-06 08:39 UTC, desaianiruddh commented on Practical-8/user-management-react-app/src/reducers/userManagementReducer.js
> +  switch(action.type) {
de-structure type and payload

2022-04-06 09:23 UTC, desaianiruddh approved these changes

2022-04-06 10:21 UTC, harshpatel-javascript commented on Practical-8/user-management-react-app/src/components/SignUp/SignUp.css
> +  background-color: red;
keep color values in  same format.

2022-04-06 10:24 UTC, harshpatel-javascript approved these changes

2022-04-08 04:39 UTC, sheth-jay requested changes

2022-04-08 04:39 UTC, sheth-jay commented on Practical-8/user-management-react-app/src/components/HomePage/Home.js
> +  const userDetails = useSelector((state) => state.userManagementReducer.userDetails)
Always use hooks at top. And add semicolons to show line end.

2022-04-08 06:01 UTC, sheth-jay approved these changes

2022-04-11 11:02 UTC, merged